env:
  node: true
  es6: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:prettier/recommended
  - plugin:jest/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
rules:
  no-unused-vars: off
